### ISSUE TITLE
failed to __setstate__()

### ISSUE THREAD

**Issue by tkram01** [irmen/Pyrolite#75]
Getting this error when unpickling.

`Unpickler unpickler = new Unpickler();
        ClassDict o = (ClassDict) unpickler.loads(Base64.getDecoder().decode(s));`

`Exception in thread "main" net.razorvine.pickle.PickleException: failed to __setstate__()
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:409)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:234)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:123)
        at net.razorvine.pickle.Unpickler.loads(Unpickler.java:136)
        at com.vrtx.jdesign.data.DesignDocument.main(DesignDocument.java:91)
Caused by: java.lang.NoSuchMethodException: net.razorvine.pickle.objects.ClassDict.__setstate__([B)
        at java.base/java.lang.Class.getMethod(Class.java:2113)
        at net.razorvine.pickle.Unpickler.load_build(Unpickler.java:406)
        ... 4 more`

**Comment by irmen** [comment]
@tkram01 wasn't there a problem after all?
